image: go1.2

script:
  - env
  - go get -d -t
  - go test

services:
  - schimmy/mongodb:2.6
notify:
  email:
    recipients:
      - drone@clever.com
  hipchat:
    room: Clever-Dev-CI
    token: {{hipchatToken}}
    on_started: true
    on_success: true
    on_failure: true
